FROM python:3.12

WORKDIR /code

RUN apt-get update && apt-get install -y dos2unix

COPY ./requirements.inference.txt /code/requirements.inference.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.inference.txt

COPY ./scripts/inference_run.sh /code/scripts/inference_run.sh
RUN dos2unix /code/scripts/inference_run.sh && chmod +x /code/scripts/inference_run.sh

# Don't copy source code - will be mounted as volume for development

ENV PYTHONPATH=src

CMD ["/code/scripts/inference_run.sh"]