FROM python:3.12

WORKDIR /code

RUN apt-get update && apt-get install -y dos2unix netcat-openbsd iputils-ping dnsutils

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./scripts/wait-for-it.sh /code/scripts/wait-for-it.sh
COPY ./scripts/run.sh /code/scripts/run.sh
RUN dos2unix /code/scripts/*.sh && chmod +x /code/scripts/*.sh

ENV PYTHONPATH=src

CMD ["/code/scripts/wait-for-it.sh", "db:3306", "-t", "60", "--", "/code/scripts/run.sh"]